# quick reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# mouse
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind -r "<" swap-window -d -t -1 # move a janela para a esquerda da listagem de janelas
bind -r ">" swap-window -d -t +1 # move a janela para a  direita da listagem de janelas
bind c new-window -c "#{pane_current_path}" # faz com que os novos paineis ou janelas sejam criados no mesmo caminho que o anterior

bind Space last-window # Vai para a ultima janela abrida

bind + split-window -hc "#{pane_current_path}" # divide a janela horizontalmetne
bind - split-window -vc "#{pane_current_path}" # divide a janela verticalmente

# Prefix + ! coloca um painel em uma janela separada
# junta uma janela em outra formando dois paineis de uma mesma janela
bind j choose-window 'join-pane -h -s "%%"' # junta horizontalmente
bind J choose-window 'join-pane -s "%%"'    # junta verticalmente

# More history
set-option -g history-limit 5000

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin "nordtheme/tmux"
set -g status-right '#(gitmux "#{pane_current_path}")'
set -g status-right '#{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage} | %a %h-%d %H:%M '

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
