unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind-key b set-option status


set -g mouse on
set -g renumber-windows on
set -g allow-rename on
set -g set-titles on
set -g detach-on-destroy off

setw -g aggressive-resize on
setw -g monitor-activity on

set -g base-index 1
set -g pane-base-index 1

bind c new-window -c "#{pane_current_path}" # faz com que os novos paineis ou janelas sejam criados no mesmo caminho que o anterior

bind Space last-window # Vai para a ultima janela abrida

unbind '"'
unbind %
bind + split-window -hc "#{pane_current_path}" # divide a janela horizontalmetne
bind - split-window -vc "#{pane_current_path}" # divide a janela verticalmente

# Prefix + ! coloca um painel em uma janela separada
# junta uma janela em outra formando dois paineis de uma mesma janela
bind j choose-window 'join-pane -h -s "%%"' # junta horizontalmente
bind J choose-window 'join-pane -s "%%"'    # junta verticalmente

# More history
set-option -g history-limit 5000
set-option -g status-position bottom

# Switch between previous and next windows with repeatable
bind -r n next-window
bind -r p previous-window
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "nordtheme/tmux"

set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'

run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run '~/.tmux/plugins/tpm/tpm'
